language: python

python:
  - "2.7"
  - "3.5"
  
install:
  - pip install coveralls
  
script:
  - coverage run hello.py
  
after_success:
  COVERALLS_REPO_TOKEN=ZudwQ338bf2qgiov9ygQP3cuZvCxh1p4j coveralls
  
